### PR TITLE
Release 1.2.5

### LINKED ISSUE #62: Bug: Crash on SettingsActivity.addToFavoritesContainer()
**Stacktrace**
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3488)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3635)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2175)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7860)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1068)
Caused by: java.lang.NullPointerException: 
  at fnsb.macstransit.Activities.SettingsActivity.addToFavoritesContainer (SettingsActivity.java:148)
  at fnsb.macstransit.Activities.SettingsActivity.onCreate (SettingsActivity.java:108)
  at android.app.Activity.performCreate (Activity.java:7955)
  at android.app.Activity.performCreate (Activity.java:7944)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3463)
```

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A01
 - OS: Android 10
 - App version: Release 1.2.4

**Additional context**
Information gathered form google play console

### LINKED ISSUE #63: Bug: Null pointer exception on Route.enableFavoriteRoutes()
**Describe the bug**
Null pointer exception thrown on enableFavoriteRoutes

**Smartphone (please complete the following information):**
 - OS: Android 10
 - App version: Release 1.2.4

**Additional context**
Crash obtained through Google Play Console

### PR DESCRIPTION
**Pull request by yeSpud**
Fixed crash on enabling favorited routes

Fixes #63 
Fixes #62

### CODE REVIEW

**Comment by yeSpud** [comment]
Verify with beta

**Review by yeSpud — COMMENTED** [review]
Needs version updates and documentation

File: app/src/main/java/fnsb/macstransit/Activities/ActivityListeners/StopClicked.java [hunk 1]
```diff
@@ -418,17 +417,29 @@ private void showMarker(@NonNull com.google.android.gms.maps.model.Marker marker
 		// Get the name of the stop.
 		String name = marker.getTitle();
 
+		// If the name is null return early.
+		if (name == null) {
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/Activities/ActivityListeners/StopClicked.java:421]: Forgot to update version

File: app/src/main/java/fnsb/macstransit/RouteMatch/SharedStop.java [hunk 2]
```diff
@@ -226,19 +226,53 @@ public SharedStop(LatLng latLng, String stopName, @NonNull Route[] routes) {
...
 	public static boolean areEqual(@NonNull SharedStop sharedStop, @NonNull Stop stop) {
 
+		LatLng sharedLoc = sharedStop.circleOptions[0].getCenter(), stopLoc = stop.circleOptions.getCenter();
+
 		// Compare names.
 		boolean nameMatch = sharedStop.name.equals(stop.name),
 
 				// Compare latitude.
-				latitudeMatch = sharedStop.circleOptions[0].getCenter().latitude == stop.circleOptions.getCenter().latitude,
+				latitudeMatch = sharedLoc.latitude == stopLoc.latitude,
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/RouteMatch/SharedStop.java:235]: Forgot to update version

File: app/src/main/java/fnsb/macstransit/RouteMatch/Stop.java [hunk 3]
```diff
@@ -286,11 +238,14 @@ public static boolean isDuplicate(Stop stop, Stop[] stopArray) {
...
 
+			// Get the latitude and longitudes of the circles.
+			LatLng loc1 = stop.circleOptions.getCenter(), loc2 = stopArrayItem.circleOptions.getCenter();
+
 			// Check if the following match.
 			boolean nameMatch = stop.name.equals(stopArrayItem.name),
 					routeMatch = stop.route.routeName.equals(stopArrayItem.route.routeName),
-					latitudeMatch = stop.circleOptions.getCenter().latitude == stopArrayItem.circleOptions.getCenter().latitude,
-					longitudeMatch = stop.circleOptions.getCenter().longitude == stopArrayItem.circleOptions.getCenter().longitude;
+					latitudeMatch = loc1.latitude == loc2.latitude,
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/RouteMatch/Stop.java:247]: Forgot to update version

File: app/src/main/java/fnsb/macstransit/Threads/UpdateThread.java [hunk 4]
```diff
@@ -17,16 +17,14 @@
...
-		PAUSE, RUN, STOP
-	}
+	public static final long DEFAULT_FREQUENCY = 10 * 1000;
 
 	/**
-	 * The current state of the Update Thread. Default state is stopped.
+	 * Object used for synchronization between the maps activity and the update thread.
 	 */
-	public STATE state = STATE.STOP;
+	public final Object LOCK = new Object();
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/Threads/UpdateThread.java:27]: Forgot to update version

**Review by yeSpud — COMMENTED** [review]
Update comments

**Comment by yeSpud** [comment]
Verify with beta
