### PR TITLE
Release 1.2

### LINKED ISSUE #54: Bug: Splashscreen is displayed incorrectly in landscape mode
**Describe the bug**
The progress bar (and potentially button), and icon are all squished in landscape mode

**Screenshots**
Screenshot_1595299245

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T & Emulator
 - OS: Android 10 & Android 4.4 (Kitkat)
 - App version Release 1.1.1 & Release 1.2

### LINKED ISSUE #56: Bug: [Short description of the bug]
**Describe the bug**
The bus fares page has changed to https://www.fnsb.gov/352/Bus-Fares

### LINKED ISSUE #59: Bug: Reloading maps view causes favorited routes to be selected regardless of menu check
**Describe the bug**
Whatever routes are favorited are selected upon loading the MapsActivity (like from returning from the SettingsActivity, or going to the home screen, and returning the app). When doing so the checkboxes in the dropdown are not updated correctly.

**To Reproduce**
1. Launch the app with favorite routes.
2. Change which routes are selected from the drop-down menu.
3. Go to a different view/activity.
4. Return to the MapsActivity.
5. Notice how the selected routes have seemingly re-enabled favorited routes, but not selected them from the drop-down.

**Expected behavior**
Favorite routes should only be pre-selected upon the first load coming from SplashActivity.

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 10.
 - App version: Release 1.2.2

### PR DESCRIPTION
**Pull request by yeSpud**
Fixes #59 
Fixes #56 
Fixes #54 
Implements #57 
Implements #53 
Implements #52 
Implements #51 
Implements #50 
Implements #49

### CODE REVIEW

File: app/src/main/java/fnsb/macstransit/Activities/ActivityListeners/StopDeselected.java [hunk 1]
```diff
@@ -1,15 +1,16 @@
...
-import android.util.Log;
+import fnsb.macstransit.RouteMatch.MarkedObject;
 
 /**
  * Created by Spud on 2019-11-11 for the project: MACS Transit.
  * <p>
  * For the license, view the file titled LICENSE at the root of the project
  *
- * @version 1.1
+ * @version 1.3
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/Activities/ActivityListeners/StopDeselected.java:10]: Did a version get skipped?

File: app/src/main/java/fnsb/macstransit/Activities/PopupWindow.java [hunk 2]
```diff
@@ -15,9 +15,10 @@
  * <p>
  * For the license, view the file titled LICENSE at the root of the project
  *
- * @version 1.1
+ * @version 1.3
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/Activities/PopupWindow.java:18]: Was a version skipped?

File: app/src/main/java/fnsb/macstransit/RouteMatch/MarkedObject.java [hunk 3]
```diff
@@ -2,23 +2,40 @@
...
 import com.google.android.gms.maps.model.MarkerOptions;
 
 /**
  * Created by Spud on 2019-11-20 for the project: MACS Transit.
  * <p>
- * For the license, view the file titled LICENSE at the root of the project
+ * For the license, view the file titled LICENSE at the root of the project.
  *
- * @version 1.1
+ * @version 1.1.
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/RouteMatch/MarkedObject.java:15]: Version not updated

File: app/src/main/java/fnsb/macstransit/RouteMatch/SharedStop.java [hunk 4]
```diff
@@ -2,265 +2,357 @@
...
+import fnsb.macstransit.Activities.MapsActivity;
 
 /**
  * Created by Spud on 2019-11-01 for the project: MACS Transit.
  * <p>
- * For the license, view the file titled LICENSE at the root of the project
+ * For the license, view the file titled LICENSE at the root of the project.
  *
- * @version 2.0
+ * @version 2.0.
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/RouteMatch/SharedStop.java:20]: Version not updated

File: app/src/main/java/fnsb/macstransit/RouteMatch/Stop.java [hunk 5]
```diff
@@ -2,131 +2,334 @@
...
+import org.json.JSONException;
 
 /**
  * Created by Spud on 2019-10-18 for the project: MACS Transit.
  * <p>
- * For the license, view the file titled LICENSE at the root of the project
+ * For the license, view the file titled LICENSE at the root of the project.
  *
- * @version 1.3
+ * @version 1.3.
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/RouteMatch/Stop.java:20]: Version not updated

File: app/src/main/res/layout/settings.xml [hunk 6]
```diff
@@ -0,0 +1,182 @@
+<?xml version="1.0" encoding="utf-8"?>
+<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:app="http://schemas.android.com/apk/res-auto"
+    android:layout_width="match_parent"
+    android:layout_height="match_parent"
+    android:background="@color/colorPrimaryDark"
```
Comment (yeSpud) [inline app/src/main/res/layout/settings.xml:6]: Possible overdraw?

File: app/src/main/res/layout/splashscreen.xml [hunk 7]
```diff
@@ -1,32 +1,29 @@
 <?xml version="1.0" encoding="utf-8"?>
-<androidx.constraintlayout.widget.ConstraintLayout
+<LinearLayout
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
     android:id="@+id/linearLayout"
+    android:orientation="vertical"
     android:layout_width="match_parent"
     android:layout_height="match_parent"
     android:background="@color/colorPrimaryDark">
```
Comment (yeSpud) [inline app/src/main/res/layout/splashscreen.xml:9]: Possible overdraw?

File: app/src/test/java/fnsb/macstransit/Helper.java [hunk 8]
```diff
@@ -0,0 +1,139 @@
...
+ * <p>
+ * For the license, view the file titled LICENSE at the root of the project.
+ *
+ * @version 1.0
+ * @since Release 1.2.
+ */
+class Helper {
+
+	/**
+	 * TODO Documentation
```
Comment (yeSpud) [inline app/src/test/java/fnsb/macstransit/Helper.java:29]: Because these arent production files this is fine, but in the future, these should be filled out

**Review by yeSpud — COMMENTED** [review]
Should fix these.

**Review by yeSpud — COMMENTED** [review]
Verify with beta
