### PR TITLE
Release 1.1

### LINKED ISSUE #13: Phantom markers
When de-selecting a route from the menu, it may disappear, only to reappear, but not update position or be included in any of the arrays.

Seems to happen when the route is de-selected near the end of the timeout of the update loop

### LINKED ISSUE #42: Bug: Time shown around noon is wrong on 12 hour mode
**Describe the bug**
When on 12 hour mode, noon is shown as 0:xx AM

**To Reproduce**
1. Click on stop that has one around noon
2. Observe that the time is wrong

**Expected behavior**
It should display 12:xx PM

**Screenshots**
Screenshot_1580761302

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android Pie
 - App version: Release 1.0

### PR DESCRIPTION
**Pull request by yeSpud**
* Fixed #13 
* Implemented #38 
* Implemented #36 
* Fixed #42 
* Implemented #43

### CODE REVIEW

File: app/src/main/java/fnsb/macstransit/Activities/ActivityListeners/AdjustZoom.java [hunk 1]
```diff
@@ -47,7 +47,7 @@ public AdjustZoom(MapsActivity activity) {
 	public static void adjustCircleSize(float zoomLevel, SharedStop[] sharedStops) {
 		// Get how much it has changed from the default zoom (11).
 		float zoomChange = 11.0f / zoomLevel;
-		Log.d("CameraChange", "Zoom change: " + zoomChange);
+		// Log.d("adjustCircleSize", "Zoom change: " + zoomChange);
```
Comment (yeSpud) [inline app/src/main/java/fnsb/macstransit/Activities/ActivityListeners/AdjustZoom.java]: This should be removed
